chore(eslint): Fail the new git workflow if `git diff` fails

diff --git a/.github/workflows/lint.diff.yml b/.github/workflows/lint.diff.yml
--- a/.github/workflows/lint.diff.yml
+++ b/.github/workflows/lint.diff.yml
@@ -22,7 +22,7 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: ${{ github.base_ref }}
-      - name: Checkout PR topic ref
+      - name: Checkout PR merge ref
         uses: actions/checkout@v2
         with:
           ref: ${{ github.ref }}
@@ -37,4 +37,16 @@ jobs:
       - name: Build all
         run: npm run buildall
       - name: Run eslint
-        run: npx eslint --no-error-on-unmatched-pattern $(git diff --name-only origin/$GITHUB_BASE_REF)
+        run: |
+          changed_files="$(git diff --name-only origin/${{ github.base_ref }})"
+          if (( $? )); then
+            echo "Failed diff against origin/${{ github.base_ref }}"
+            exit 1
+          else
+            echo "Changed files:"
+            echo "$changed_files"
+            echo
+            echo "Running eslint"
+            echo
+            npx eslint --no-error-on-unmatched-pattern $changed_files
+          fi
